version: '3.8'
services:
  postgres:
    container_name: 'malwarebytes-postgres'
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  postgres:
