version: '3.8'
services:
  api:
    container_name: 'shopping-backend'
    stdin_open: true
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    env_file:
      - ./.env.development
    restart: always
    volumes:
      - ./:/usr/backend_api
      - /backend_api/node_modules

  postgres:
    container_name: 'shopping-postgres'
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=shopping
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
